infrastructure/main.tf

https://tools.hmcts.net/jira/browse/BPS-806
- Jenkins library needs infra folder for deployment https://github.com/hmcts/cnp-jenkins-library/blob/master/vars/sectionDeployToEnvironment.groovy#L28
```
[ ] Yes
[x ] No
```

Added basic main.tf file to add infra foler

---

charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml

add required setting to use secrets
```
[ ] Yes
[x] No
```

chart fix to use secrets

---

build.gradle
charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/requirements.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/IntegrationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerPublisher.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/QueueClientsConfiguration.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml
src/smokeTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/DummySmokeTest.java

queue config added
[ ] Yes
[x] No

add queue configurations

---

charts/bulk-scan-payment-processor/values.yaml

Service bus should be disabled by default

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/exceptions/InvalidMessageException.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/exceptions/MessageProcessingException.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/MessageProcessingResult.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/MessageProcessingResultType.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/PaymentInfo.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/PaymentMessage.java

adding the queue model and exceptions
[ ] Yes
[x] No

add model and exceptions

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.yaml

namespace updated to bsp from rpe.
```
[ ] Yes
[x] No
```

namespace update to bsp

---

build.gradle

gradle changes, add Feign dependency and fix gradle test process and exclude junit 4
bump the junit versions
[ ] Yes
[x] No

Gradle changes

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/main/resources/application.yaml

config changes to call payhub 
```
[ ] Yes
[x] No
```

config changes for pay-hub call

---

infrastructure/main.tf
infrastructure/variables.tf

Splitting #33 into 2 PRs as the build is failing to find the s2s secret in bulkscan key vault.
This PR copies the microservice secret from s2s vault to bulkscan vault.
Once this pr is merged, #33 build should be fixed.
```
[ ] Yes
[x] No
```

Bps 765 copy s2s secret to bulkscan vault

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClientTest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/Application.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClient.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/request/PaymentRequest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/response/PaymentResult.java

adding Feign client and integration tests
```
[ ] Yes
[x] No
```

Feign client and tests

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.aat.template.yaml
charts/bulk-scan-payment-processor/values.yaml

Correct me if I'm wrong but AAT step:
> Warning: Merging destination map for chart 'bulk-scan-payment-processor'. Cannot overwrite table item 'environment'
```
[ ] Yes
[x] No
```

Fix master pipeline

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClientTest.java
src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClient.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/AuthConfig.java
src/main/resources/application.yaml

Add service authorization header to Payhub client
```
[ ] Yes
[x] No
```

Add Service Auth header to Payhub client

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/exceptions/InvalidMessageException.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java

parser from binary azure message to paymentMessage model
[ ] Yes
[x] No

remove static payment parser and add test cases for parser

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfiguration.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/exception/SiteConfigurationException.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java

map po box to site id
[ ] Yes
[x] No

Add pobox to siteidmap

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapper.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/PaymentMessage.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java

change field name in payment message to match with orchestrator
```
[ ] Yes
[x] No
```

change field name in payment message to match with orchestrator and add log

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/PaymentMessage.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapperTest.java

Extend payment queue message with service name - needed for talking to CCD.
```
[ ] Yes
[x] No
```

Extend payment queue message with service name

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java

refactor logging
```
[ ] Yes
[x] No
```

refactor logs

---

src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClientTest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubClient.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/request/CreatePaymentRequest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/response/CreatePaymentResponse.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapper.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapperTest.java

rename payhub client  classes and client method name
class PaymentRequest  to CreatePaymentRequest
class PaymentResult to CreatePaymentResponse
method postPayments to createPayment
```
[ ] Yes
[x] No
```

rename pay-hub classes and client methods

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/BPS-824
Orchestrator will soon send two types of messages.
Labels are used to distinguish which is which.
See https://github.com/hmcts/bulk-scan-orchestrator/pull/641

Require message label

---

build.gradle
config/owasp/suppressions.xml

Update owasp suppressions
```
[ ] Yes
[x] No
```

Update owasp suppressions

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/UpdatePaymentMessage.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java

https://tools.hmcts.net/jira/browse/BPS-766
add handler to handle pay-hub update.
#62   previous stuck in the pipeline. 
```
[ ] Yes
[x] No
```

Add updatepayment handler

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java

https://tools.hmcts.net/jira/browse/BPS-766
add parser for payment update messaege
```
[ ] Yes
[x] No
```

Add update case ref parser

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapper.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/CreatePaymentMessage.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapperTest.java

rename PaymentMessage class to PaymentMessage
```
[ ] Yes
[x] No
```

rename PaymentMessage class to CreatePaymentMessage

---

charts/bulk-scan-payment-processor/values.aat.template.yaml

to enable staging pods to log azure
```
[ ] Yes
[x] No
```

enable staging to log azure

---

build.gradle

Remove not needed dependency

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/requirements.yaml
charts/bulk-scan-payment-processor/values.aat.template.yaml

###JIRA link (if applicable)
###Change description
Log fix for staging
use latest chart version
[ ] Yes
[x] No

Log fix for preview

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/BPS-766
integrate update payment process
```
[ ] Yes
[x] No
```

Update payment - process integration

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/integrationTest/resources/application-integration.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

Prepare configuration necessary for talking to IDAM and CCD, so that this application can update exception records in CCD.
```
[ ] Yes
[x] No
```

Prepare configuration necessary for talking to IDAM and CCD

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/model/UpdatePaymentMessage.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/data/producer/SamplePaymentMessageData.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java

https://tools.hmcts.net/jira/browse/BPS-766
remove service from update payment model as orchestrator can not provide
[ ] Yes
[x] No

Remove service field updatepayment

---

Jenkinsfile_CNP
infrastructure/main.tf
src/smokeTest/resources/application.conf

https://tools.hmcts.net/jira/browse/BPS-842
Add smoke tests config:
- copy payments queue secret from vault 
- set pay hub url 
```
[ ] Yes
[x] No
```

BPS-842 Add  smoke tests config

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/Application.java
src/main/resources/application.yaml

Make configuration changes necessary for using CCD client in this app, along with the already existing PayHub client and IDAM client.
```
[ ] Yes
[x] No
```

Make configuration changes necessary for using CCD client

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdClient.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/client/CompleteAwaitingDcnProcessingTest.java

Create a high-level CCD client, for marking the awaiting of payment DCN processing as completed.
```
[ ] Yes
[x] No
```

Create a high-level CCD client

---

src/smokeTest/resources/application.conf

https://tools.hmcts.net/jira/browse/BPS-842
```
[ ] Yes
[x] No```

Remove unused smoke tests config

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java

Update exception record in CCD after payment creation in PayHub.
This PR won't be merged before including functional tests, done as a different story.
```
[ ] Yes
[x] No
```

Update exception record in CCD after payment creation

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java

Update CCD only for exception records. It's possible for 'create' messages to represent service cases.
```
[ ] Yes
[x] No
```

Update CCD only for exception records

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/BPS-816
Added secrets necessary for PRs
```
[ ] Yes
[x] No
```

Update charts for func tests

---

src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

Fix the configuration issues that prevent the application from running as it's supposed to.
```
[ ] Yes
[x] No
```

Fix configuration

---

build.gradle

Bump servicebus 1.2.15 -> 1.2.18

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.yaml

fix image url as https is not working for product chart
```
[ ] Yes
[x] No
```

fix image url

---

Jenkinsfile_CNP
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java

**JIRA link (if applicable)**
https://tools.hmcts.net/jira/browse/BPS-816
**Change description**
Setting PAYMENTS_QUEUE_WRITE_CONNECTION_STRING to fix func test in AAT
```
[ ] Yes
[x] No
```

Set PAYMENTS_QUEUE_WRITE_CONNECTION_STRING to fix func test in AAT

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/requirements.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml

get ready for helm version upgrade
with new version of Helm:
ApiVersion is mandatory in helm chart
Conditions in Helm charts , indentation of the condition needs to inside the base chart.
```
[ ] Yes
[x] No
```

get ready for helm version upgrade

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/BPS-933
comment about liveness alerts dependency to application name
```
[ ] Yes
[ ] No
```

comment about liveness alerts dependency to application name

---

Jenkinsfile_CNP
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/variables.tf
web.config

Make the service ASE-deployable, so that it can be deployed to demo.
```
[ ] Yes
[x] No
```

Make the application ASE-deployable

---

build.gradle
config/owasp/suppressions.xml

- Update tomcat dependencies as previous version has vulnerabilities.
- Added suppression for handlebars but it is referenced only in tests.
```
[ ] Yes
[x ] No
```

Updated tomcat dependencies and added suppression

---

infrastructure/main.tf
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/BPS-986
Configured BULKSCAN service
```
[ ] Yes
[x] No
```

Configured BULKSCAN

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml

following https://github.com/hmcts/bulk-scan-payment-processor/pull/165
Flux PR: https://github.com/hmcts/cnp-flux-config/pull/1973

Add missing secrets declarations

---

src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java

Strangely only started to complain after unrelated merge got in straight after #170 PR.
```
[ ] Yes
[x] No
```

Cover extra branches introduced in #170

---

charts/bulk-scan-payment-processor/values.preview.template.yaml

TTL 15 days
```
[ ] Yes
[x] No
```

Remove deprecated usage of property in preview chart template

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java

Extend a log entry by more information (exception record ref, case ref) and make log message structure a bit more consistent.
```
[ ] Yes
[x] No
```

Minor logging improvements

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java

https://tools.hmcts.net/jira/browse/BPS-1121
use new idam-client, use openid token
```
[ ] Yes
[ ] No
```

use openid token

---

src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java

disable func test
```
[ ] Yes
[ ] No
```

disable func test

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java

Revert "disable func test (#211)"
Revert "use openid token (#207)" 
```
[ ] Yes
[x] No
```

Revert "disable func test (#211)" and Revert "use openid token (#207)" 

---

infrastructure/demo.tfvars

https://tools.hmcts.net/jira/browse/BPS-1164
```
[ ] Yes
[x ] No
```

Remove ASE as it is deployed to AKS

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/requirements.yaml

Update java chart to version 2.18.0
Related flux change: https://github.com/hmcts/cnp-flux-config/pull/3538
```
[ ] Yes
[x] No
```

Update java chart to version 2.18.0

---

Jenkinsfile_CNP

Rename secret sets in Jenkinsfile_CNP so that they accurately describe what they're for.
```
[ ] Yes
[x] No
```

Rename secret sets in Jenkinsfile_CNP

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java

https://tools.hmcts.net/jira/browse/BPS-1121
Use new idam openid
```
[ ] Yes
[ x] No
```

use new openid token 

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactory.java

#226 stuck .
remove log.
It was just to check deployment, Checked the logs in Prod, it is deployed to prod.
```
[ ] Yes
[x] No
```

remove log

---

build.gradle
config/owasp/suppressions.xml

suppress vulnerability and dependbot dependency upgrades
```
[ ] Yes
[x] No
```

arrange suppress vulnerability and dependbot dependency upgrades

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/TracingConfiguration.java

https://tools.hmcts.net/jira/browse/BPS-1201
add health separation to appinsight
```
[ ] Yes
[x] No
```

add health separation to appinsight

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/task/PaymentMessageProcessTask.java

https://tools.hmcts.net/jira/browse/BPS-1263
```
[ ] Yes
[x] No
```

Update the log message in the consume payments queue scheduled job

---

build.gradle
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/BPS-643
upgrade service bus version
```
[ ] Yes
[x] No
```

upgrade service bus version

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
This service only uses payments queue so configuration will be simple in the upcoming pr.
Note. Blocked by hmcts/bulk-scan-shared-infrastructure#187
```
[ ] Yes
[x] No
```

Expand payments queue config

---

charts/bulk-scan-payment-processor/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/QueueClientsConfiguration.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/QueueConfigurationProperties.java

Reference #263
```
[ ] Yes
[x] No
```

Replace connection string with access key and namespace

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
```
[ ] Yes
[x] No
```

Remove no longer used servicebus connection string for application

---

infrastructure/main.tf

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
This section is not used anymore. ASE deployments are disabled. Safe to remove single reference left
```
[ ] Yes
[x] No
```

Get rid of connection string reference - terraform

---

charts/bulk-scan-payment-processor/values.aat.template.yaml
src/main/resources/bootstrap.yaml

need to use all keyvault values as last time i remember there was no override. need to apply staging shared access key
```
[ ] Yes
[x] No
```

Apply all keyvault overrides for aat staging from template

---

Jenkinsfile_CNP
src/functionalTest/resources/application.yaml

PR and aat staging are using different queues. Env vars already defined just missing this config
```
[ ] Yes
[x] No
```

Fix functional tests in aat staging - missing env var

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/payhub/PayHubCallException.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java

https://tools.hmcts.net/jira/browse/BPS-1210
Logging errors from PayHub
```
[ ] Yes
[x] No
```

Logging PayHub errors

---

infrastructure/state.tf

Adds the backend state for the bulk-scan-payment-processor.
```
[ ] Yes
[X] No
```

chore: add state to payment-processor

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/BPS-1391
Removes the RG from main.tf which is causing issues on prod piepline... 
```
[ ] Yes
[ ] No
```

fix: remove the duplicated RG

---

Jenkinsfile_CNP
charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/requirements.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml

upgrade chart
```
[ ] Yes
[x] No
```

upgrade chart

---

build.gradle
config/owasp/suppressions.xml

bump versions and fix suppressions
```
[ ] Yes
[ ] No
```

bump versions and fix suppressions

---

config/owasp/suppressions.xml

suppress lang-tag-vulnerability

---

config/owasp/suppressions.xml

suppress-vulnerability

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-369
Spring boot version bump to 2.4.3
```
[ ] Yes
[X ] No
```

DTSBPS-369 - update springboot

---

build.gradle

bump core-case-data-store-client. #377 stuck

bump core-case-data-store-client

---

build.gradle

Bump idam-client from v1.5.5 to 2.0.0,  #370 stuck
```
[ ] Yes
[x] No
```

Bump idam-client from v1.5.5 to 2.0.0 

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-412
use new env var. 
```
[ ] Yes
[ ] No
```

use new env var.

---

build.gradle

dependabot-org.springframework.boot
```
[ ] Yes
[x] No
```

dependabot-org.springframework.boot

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.yaml
infrastructure/main.tf

https://tools.hmcts.net/jira/browse/DTSBPS-451
Terraform adding processor url
```
[ ] Yes
[x ] No
```

DTSBPS-451: Chart adding processor url

---

src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/BulkScanProcessorApiProxyTest.java
src/integrationTest/resources/application-integration.yaml
src/integrationTest/resources/testdata.post-processor/payments.json
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/BulkScanProcessorApiProxy.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/CustomFeignErrorDecoder.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/request/PaymentRequest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/client/processor/CustomFeignErrorDecoderTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-451
Adding processor client
```
[ ] Yes
[x ] No
```

DTSBPS-451: Adding processor client

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-451
Adding missing processor URL configuration
```
[ ] Yes
[ X] No
```

DTSBPS-451: Adding missing processor URL configuration

---

charts/bulk-scan-payment-processor/values.preview.template.yaml
src/functionalTest/resources/application.yaml
src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/Application.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/AsyncConfiguration.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/RetryConfig.java

https://tools.hmcts.net/jira/browse/DTSBPS-451
Configuration changes
```
[ ] Yes
[x ] No
```

DTSBPS-451: Configuration changes

---

build.gradle
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/Application.java

remove unnecessary spring-cloud-starter-netflix-hystrix
```
[ ] Yes
[x] No
```

DTSBPS-501 remove unnecessary spring-cloud-starter-netflix-hystrix

---

src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-521
DTSBPS-521 - remove security disabling for health
```
[ ] Yes
[x] No
```

DTSBPS-521 - remove security disabling for health

---

config/owasp/suppressions.xml

remove unnecessary suppressions
```
[ ] Yes
[x] No
```

remove unnecessary suppressions

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-627
remove unnecessary jars from dependency management
```
[ ] Yes
[x] No
```

DTSBPS-627 remove unnecessary jars from dependency management

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

upgrade gradle
```
[ ] Yes
[x] No
```

upgrade gradle

---

build.gradle

Disable scanning of .NET related binaries
```
[ ] Yes
[x] No
```

OWASP-Disable scanning of .NET related binaries

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-644
env var name changed and we do not need this one.
```
[ ] Yes
[x] No
```

DTSBPS-644 remove unused env var

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-647
DTSBPS-647 change job interval
```
[ ] Yes
[x] No
```

DTSBPS-647 change job interval

---

charts/bulk-scan-payment-processor/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-650
upgrade java-chart
```
[ ] Yes
[x] No
```

DTSBPS-650 - upgrade java-chart

---

build.gradle

downgrade 'azure-messaging-servicebus'
as there were some unprocessed messages in notification queue after down grade it picked up.
so we can skip this version
```
[ ] Yes
[x] No
```

downgrade 'azure-messaging-servicebus'

---

charts/bulk-scan-payment-processor/Chart.yaml

DTSBPS-692 bump java chart
```
[ ] Yes
[x] No
```

DTSBPS-692 bump java chart

---

src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/client/CompleteAwaitingDcnProcessingTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java

DTSBPS-695 refactor feign exceptions in tests
```
[ ] Yes
[x] No
```

DTSBPS-695 refactor feign exceptions in tests

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdClient.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParser.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/task/PaymentMessageProcessTask.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/CcdAuthenticatorFactoryTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/ccd/client/CompleteAwaitingDcnProcessingTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/JurisdictionToUserMappingTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/health/PayHubHealthIndicatorTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/PaymentRequestMapperTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-737
```
[ ] Yes
[x] No
```

Code smells

---

build.gradle

DTSBPS-755 - Bump versions.junit from 5.7.2 to 5.8.1
```
[ ] Yes
[x] No
```

DTSBPS-755 - Bump versions.junit

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/handler/PaymentMessageHandler.java

DTSBPS-389 add log
```
[ ] Yes
[x] No
```

DTSBPS-389 add log

---

charts/bulk-scan-payment-processor/values.aat.template.yaml

DTSBPS-798-remove-devApplicationInsightsInstrumentKey
```
[ ] Yes
[x] No
```

DTSBPS-798-remove-devApplicationInsightsInstrumentKey

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerPublisher.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerConfiguration.java

DTSBPS-802 upgrade spring boot 2.6.1
```
[ ] Yes
[x] No
```

DTSBPS-802 upgrade spring boot 2.6.1

---

src/integrationTest/resources/application-integration.yaml
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SwaggerConfiguration.java
src/main/resources/application.yaml

DTSBPS-802 fix swagger ui
```
[ ] Yes
[x] No
```

DTSBPS-802 fix swagger ui

---

build.gradle

remove org.apache.tomcat.embed from dependencymanagement
```
[ ] Yes
[ ] No
```

remove org.apache.tomcat.embed from dependencymanagement

---

charts/bulk-scan-payment-processor/Chart.yaml

DTSBPS-867-bump-java-chart
```
[ ] Yes
[x] No
```

DTSBPS-867 bump-java-chart

---

charts/bulk-scan-payment-processor/Chart.yaml

bump-java-chart
```
[ ] Yes
[x] No
```

bump-java-chart

---

charts/bulk-scan-payment-processor/Chart.yaml

bump java chart
```
[ ] Yes
[x] No
```

bump java chart

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.aat.template.yaml
charts/bulk-scan-payment-processor/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-886
Update secrets to use premium service bus config
```
[ ] Yes
[x] No
```

User premium Servicebus (DTSBPS-886)

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-916
Upgrade Spring Boot version to 2.6.6
```
[ ] Yes
[x] No
```

Upgrade Spring Boot version

---

config/owasp/suppressions.xml

Suppress CVE-2022-22965 and CVE-2016-1000027
```
[ ] Yes
[x] No
```

Suppress vulnerabilities

---

Dockerfile
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-939
```
[ ] Yes
[x] No
```

Fortify vulnerability

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSBPS-943
Resolve CVE-2022-24823
```
[ ] Yes
[x] No
```

Resolve CVE-2022-24823

---

config/owasp/suppressions.xml

CVE 2016 1000027 vulnerability

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1084
```
[ ] Yes
[ ] No
```

DTSBPS-1084: Added suppression

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.aat.template.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
charts/bulk-scan-payment-processor/values.yaml
infrastructure/main.tf
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1128
Add payments config for NFD
```
[ ] Yes
[x] No
```

DTSBPS-1128: Add payments config for NFD

---

src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1240
```
[ ] Yes
[x] No
```

DTSBPS-1240: Allow multiple poBoxes

---

src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfiguration.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/bulkscan/payment/processor/config/SiteConfigurationTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-1240
```
[ ] Yes
[x] No
```

DTSBPS-1240: Revert "DTSBPS-1240: Allow multiple poBoxes (#877)"

---

Dockerfile

Upgrade to 3.4.8 as suggested by Ozzie Ibrahim from #platops
```
[ ] Yes
[x] No
```

Upgrade app-insights

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1276
Cleanup suppressions
```
[ ] Yes
[x] No
```

DTSBPS-1276: Cleanup suppressions

---

config/owasp/suppressions.xml

Suppress CVE-2023-24998
```
[ ] Yes
[x] No
```

Suppress CVE-2023-24998

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1325
Fix CVE-2023-24998
```
[ ] Yes
[x] No
```

DTSBPS-1325: Fix CVE-2023-24998

---

config/owasp/suppressions.xml

Suppress CVE-2022-40152
```
[ ] Yes
[x] No
```

Suppress CVE-2022-40152

---

config/owasp/suppressions.xml

Suppress CVE-2023-1436
```
[ ] Yes
[x] No
```

Suppress CVE-2023-1436

---

config/owasp/suppressions.xml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

update to supp for cve introduced by spring library

---

charts/bulk-scan-payment-processor/values.aat.template.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

changing to use premium namespace thatll change sku eventually

---

Jenkinsfile_CNP
build.gradle
charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.preview.template.yaml
config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/FunctionalQueueConfig.java
src/functionalTest/resources/application.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

attempting to fix sb in preview

---

Jenkinsfile_CNP
src/functionalTest/resources/application.yaml

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

fixing master

---

build.gradle
charts/bulk-scan-payment-processor/Chart.yaml
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties
infrastructure/state.tf

https://tools.hmcts.net/jira/browse/FACT-1698
All relevant Renovate PRs have been merged into this branch except:
- LaunchDarkly version 7.x which introduces a breaking change - [Ticket](https://tools.hmcts.net/jira/browse/FACT-1730)
**Major Version Jumps:**
- Openfeign V12 to V13
```
[ ] Yes
[x] No
```

FACT-1698 Renovate Dependencies Update

---

README.md
build.gradle
config/owasp/suppressions.xml

cve updates

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/bulk-scan-payment-processor/Chart.yaml

https://tools.hmcts.net/jira/browse/FACT-1881
trying to change to imported image and bumps
```
[ ] Yes
[x] No
```

FACT-1881 added env lines to jenkfiles

---

build.gradle

https://tools.hmcts.net/jira/browse/FACT-1906
update payment processor dependancies
```
[ ] Yes
[x] No
```

FACT-1906 update dependancies

---

src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/JmsPaymentForExceptionRecordTest.java
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/PaymentForExceptionRecordTest.java
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/CaseSearcher.java
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/ExceptionRecordCreator.java
src/functionalTest/java/uk/gov/hmcts/reform/bulkscan/payment/processor/helper/JmsPaymentsMessageSender.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/servicebus/JmsPaymentMessageProcessor.java

Local Dev Env Tests running on Bulk Scan Payment Processor

updates to get func tests working locally

---

lib/applicationinsights.json

Reverts hmcts/bulk-scan-payment-processor#1206

Revert "FACT-2013 app insights refine logging"

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-2113

FACT-2113 Dec CVEs

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

dependancy updates
```
[ ] Yes
[x] No
```

FACT-2294 dependancy updates

---

src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentHubHandlerService.java
src/main/java/uk/gov/hmcts/reform/bulkscan/payment/processor/service/PaymentService.java

Add some logging

---

charts/bulk-scan-payment-processor/Chart.yaml
charts/bulk-scan-payment-processor/values.aat.template.yaml
charts/bulk-scan-payment-processor/values.yaml

https://tools.hmcts.net/jira/browse/FACT-2133
Switch to new app insights.
```
[ ] Yes
[x] No
```

FACT-2133 Switch to new app insights
